### ISSUE TITLE
As a player, I want to select the song being played so that I can receive points.

### ISSUE THREAD

**Issue by TMGPH** [gytanzo/MusicalChairs#4]
**Acceptance Tests:**

*Test 1*
1) Open the app on https://ubcse442-musicalchairs.herokuapp.com
2) If you are logged in continue on, otherwise sign-in with the username "xyz" and the password "Xyz12345@".
3) Click the 'Play Game' button.
4) Click Classic Mode.
5) A game screen appears. You start with 0 points.
6) A clip of a song will begin playing, and four options are presented.
7) Click the A button ten times. When the correct song option is selected you will receive points.

**Comment by rafimoh** [comment]
Acceptance Tests:
*Test 1*
1) Launch a game session to begin music quiz and ensure starting points are 0
2) Ensure a music snippet is being played with there being 4 options to choose from
3) Verify that a correct choice exists
4) Verify that upon clicking correct choice, points are updated on player point total
